In [ ]:
#Assigment 2D and 3D ones
np.ones((2))

# Assigment lets try 
np.mean()
np.std()
np.min()
np.max()

In [2]:
import numpy as np
np.ones((2,3))    #2D array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
#3D array 
np.ones((2,2,3))  

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [4]:
a = np.array([[33,54,77],
              [17,49,89],
              [71,39,99]])

In [5]:
#mean
np.mean(a)

58.666666666666664

In [6]:
#std 
np.std(a)

25.673159351959608

In [7]:
#min
np.min(a)

17

In [8]:
#max
np.max(a)

99

In [9]:
# cloumnwise mean
np.mean(a,axis=0) 

array([40.33333333, 47.33333333, 88.33333333])

In [10]:
# cloumnwise std 
np.std(a,axis=0) 

array([22.64705034,  6.23609564,  8.99382504])

In [14]:
#cloumnwise min
np.min(a,axis=0)

array([17, 39, 77])

In [15]:
#cloumnwise max
np.max(a,axis=0)

array([71, 54, 99])

In [16]:
# rowwise mean
np.mean(a,axis=1)

array([54.66666667, 51.66666667, 69.66666667])

In [17]:
# rowwise std
np.std(a,axis=1)

array([17.9691093 , 29.45429605, 24.51303508])

In [18]:
#rowwise min
np.min(a,axis=1)

array([33, 17, 39])

In [19]:
#rowwise max
np.max(a,axis=1)

array([77, 89, 99])